#!/bin/bash

# A backup utility that watches folder and automatically
# copies their data using rclone
#
# Author: Ilyess Bachiri
# Copyright (c) 2020-present Ilyess Bachiri

throw_error() {
    echo "ERROR: $1"
    exit 1
}

if [[ -z "$1" || -z "$2" ]]; then
    throw_error "Missing argument. Usage: autobackup FOLDERS REMOTES"
fi

IFS=',' read -ra folders <<< $1

for i in ${folders[@]}; do
    if [[ ! -d "$i" ]]; then
        throw_error "No directory $i"
    fi
done

IFS=',' read -ra remotes <<< $2

configured_remotes=($(rclone listremotes))

for r in ${remotes[@]}; do
    found=0
    for i in ${configured_remotes[@]}; do
        if [[ "$i" == "$r:" ]]; then
            found=1
        fi
    done

    if [[ "$found" -eq 0 ]]; then
        throw_error "Unknown remote $r. To configure it run: rclone config"
    fi
done

backup() {
    target=$(basename $1)

    for r in ${remotes[@]}; do
        echo "Backing up $1 to $r"
        rclone copy -v $1 $r:$target
    done

    echo "Backup complete of $1 "
}

process_event() {
    echo "Processing event $@"

    # TODO Read file ignore list from args (config?)
    if [[ $3 != "4913" ]]; then
        backup $1
    fi
}

while true; do
    event=$(echo ${folders[@]} | xargs inotifywait -r -e modify,create,delete,move)
    process_event $event &
done
